### ISSUE TITLE
Anyway to bypass the netstandard2.0 limitation?

### ISSUE THREAD

**Issue by AxelHu** [jonatan1024/CompileTimeExecution#1]
Using preprocessor symbol to bypass the add only restriction is really an amazing idea, I followed your way to do some const calculation before compile.

It works fine in netstandard2.0, but in my current project I need net5 stuff. Emit and Assembly.Load is successful but the it fails to load related assembly on GetTypes().

I checked the roslyn repo and the restriction is still the same, do you have any idea to bypass this limitation?

**Comment by jonatan1024** [comment]
The easiest solution is to simply isolate whatever you need to precompute into a separate netstandard2.0 project. Is this viable for you?

**Comment by AxelHu** [comment]
I think this is the best solution currently, I'll do it with all constants(with calculation), thanks.
